version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      JWT_SECRET_KEY: abc1234
      URL: http://localhost:8000
      LOG_DIRECTORY: /src/logs
    volumes:
      - ./logs:/src/logs
